config/routes.rb
MasterpieceBeersDeux::Application.routes.draw do
  devise_for :users,:controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :beer_labels do
    member do
      get 'upvote'
      get 'downvote'
    end

  resources :comments do
    member do
      get 'upvote'
      get 'downvote'
    end
  end
end

  root 'beer_labels#index'

end

app/models/beer_label.rb
class BeerLabel < ActiveRecord::Base

  has_many :comments,
    inverse_of: :beer_label,
    dependent: :destroy

  accepts_nested_attributes_for :comments, allow_destroy: true

  belongs_to :user,
    inverse_of: :beer_labels
  has_many :votes,
    as: :voteable

  validates_presence_of :beer_name
  validates_presence_of :brewery
  validates_presence_of :origin
  validates_presence_of :user_id

  # validates_format_of :origin, with: /\A[a-zA-Z]+\z/

  mount_uploader :image, ImageUploader

  state_machine :state, :initial => :pending do
    
    event :reject do
      transition :pending => :rejected
    end

    event :approve do
      transition :pending => :approved
    end
  end

  acts_as_url :beer_name

  def to_param
    url
  end

end

app/controllers/beer_labels_controller.rb
class BeerLabelsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :destroy]

  def index
    @q = BeerLabel.search(params[:q])
    @beer_labels = @q.result(distinct: true)
  end

  def new
    @beer_label = BeerLabel.new
  end

  def create
    @beer_label = BeerLabel.new(beer_label_params)
    @beer_label.user = current_user
    if @beer_label.save
      redirect_to @beer_label
      flash[:notice] = "Beer label successfully added"
    else
      render :new
    end
  end

  def show
    @beer_label = BeerLabel.find_by_url(params[:id])
    @vote = Vote.new
  end

  def edit
    @beer_label = BeerLabel.find_by_url(params[:id])
  end

  def update
    @beer_label = BeerLabel.find_by_url(params[:id])

    if @beer_label.update(beer_label_params)
      redirect_to beer_label_path(@beer_label)
    else
      render action: 'edit'
    end      
  end

  def destroy
    @beer_label = BeerLabel.find_by_url(params[:id])
    @beer_label.destroy

    redirect_to beer_labels_path
  end

  def upvote
    vote(1)
  end

  def downvote
    vote(-1)
  end

  protected
  def beer_label_params
    params.require(:beer_label).permit(:beer_name, :brewery, :origin, :description, :tag, :image, :comment)
  end

  def vote(value)
    @beer_label = BeerLabel.find_by_url(params[:id])
    check_vote
    @beer_label_vote.like = value
    @beer_label_vote.user = current_user
    @beer_label_vote.save
    check_beer_label_score
    redirect_to @beer_label
  end

  def check_beer_label_score
    if Vote.score(@beer_label) == 5
      @beer_label.approve
    elsif Vote.score(@beer_label) == -5
      @beer_label.reject
    end
  end

  def check_vote
    if @beer_label.votes.where(user_id: current_user.id).any?
      @beer_label_vote = @beer_label.votes.where(user_id: current_user.id).first
    else
      @beer_label_vote = @beer_label.votes.new
    end
  end

end

app/views/beer_labels/edit.html.erb
<div class="row new-beer-form">
  <div class="col-md-4 col-md-offset-4">
    <h2>Edit Beer Label</h2>
    <%= image_tag @beer_label.image_url(:thumb).to_s %>
    <%= simple_form_for @beer_label, :html => {:multipart => true} do |f| %>
      <%= f.input :beer_name, label: "Beer Name" %>
      <%= f.input :brewery %>
      <%= f.input :origin, collection: Country::COUNTRIES, include_blank: 'Select...', input_html: { class: "chosen-select" } %>
      <%= f.input :description %>
      <%= f.input :tag %>
      <%= f.input :image, input_html: {id: 'image'} %><br/ >
      <div id="image_preview"></div>
      <%= f.button :submit, "Update Beer Label", class: "btn-primary btn-lg" %>
      <div><%= link_to 'Back Home', beer_labels_path %></div>
    <%- end -%>
  </div>
</div>

<% content_for :extra_footer do %>
  <script>
    function handleFileSelect(evt) {

      $('#image_preview img').remove(); // Removes image preview if one already exists

      var files = evt.target.files; // FileList object

      // Loop through the FileList and render image files as thumbnails.
      for (var i = 0, f; f = files[i]; i++) {

        // Only process image files.
        if (!f.type.match('image.*')) {
          continue;
        }

        var reader = new FileReader();

        // Closure to capture the file information.
        reader.onload = (function(theFile) {
          return function(e) {
              $('#image_preview').append('<img src="' + e.target.result + '" class="thumbnail"/>')

          };
        })(f);

        // Read in the image file as a data URL.
        reader.readAsDataURL(f);
      }
    }

    document.getElementById('image').addEventListener('change', handleFileSelect, false);


    $(".chosen-select").chosen()
  </script>
<% end %>

app/views/beer_labels/index.html.erb
<div class="row top-row">
  <div class="col-md-7 col-md-offset-1">
    <%= search_form_for @q do |f| %>
      <%= f.label :beer_name_cont %>
      <%= f.text_field :beer_name_cont %>
      <%= f.submit %>
    <% end %>
  </div>
  <div class="col-md-4 pull-right">
    <% if user_signed_in? %>
     <%= link_to 'Upload New Beer Label', new_beer_label_path, class: "btn btn-primary btn-lg" %>
    <% end %>
  </div>
</div>

<div class="row label-rows">
  <div class="col-md-10 col-md-offset-1">
  <% if user_signed_in? %>
    <% @beer_labels.each do |label| %>
    <div class="beer_label">
      <%= link_to image_tag(label.image_url(:index_thumb)), beer_label_path(label), class: "labels-frontpage", input_html: { rel: "shadowbox" } %>
    </div>
    <%- end -%>
  <% else %>
    <% @beer_labels[0..15].each do |label| %>
    <div class="beer_label">
      <%= link_to image_tag(label.image_url(:index_thumb)), beer_label_path(label), class: "labels-frontpage", input_html: { rel: "shadowbox" } %>
    </div>
    <%- end -%>
  <% end %>
  </div>
</div>

app/views/beer_labels/new.html.erb
<div class="row new-beer-form">
  <div class="col-md-4 col-md-offset-4">
    <h2>New Beer Label</h2>
    <%= simple_form_for @beer_label, :html => {:multipart => true} do |f| %>
      <%= f.input :beer_name, label: "Beer Name" %>
      <%= f.input :brewery %>
      <%= f.input :origin, collection: Country::COUNTRIES, include_blank: 'Select...', input_html: { class: "chosen-select" } %>
      <%= f.input :description %>
      <%= f.input :tag %>
      <%= f.input :image, input_html: {id: 'image'} %><br/ >
      <div id="image_preview"></div>
      <%= f.button :submit, "Add Beer Label", class: "btn-primary btn-lg" %>
      <div><%= link_to 'Back Home', beer_labels_path %></div>
    <%- end -%>
  </div>
</div>


<% content_for :extra_footer do %>
  <script>
    function handleFileSelect(evt) {

      $('#image_preview img').remove(); // Removes image preview if one already exists

      var files = evt.target.files; // FileList object

      // Loop through the FileList and render image files as thumbnails.
      for (var i = 0, f; f = files[i]; i++) {

        // Only process image files.
        if (!f.type.match('image.*')) {
          continue;
        }

        var reader = new FileReader();

        // Closure to capture the file information.
        reader.onload = (function(theFile) {
          return function(e) {
              $('#image_preview').append('<img src="' + e.target.result + '" class="thumbnail"/>')

          };
        })(f);

        // Read in the image file as a data URL.
        reader.readAsDataURL(f);
      }
    }

    document.getElementById('image').addEventListener('change', handleFileSelect, false);


    $(".chosen-select").chosen()
  </script>
<% end %>

app/views/beer_labels/show.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-2">
    <%= image_tag @beer_label.image_url(:show_thumb).to_s %>
  </div>
  <div class="col-md-5">
    <div class="facts-section">
      <dl class="dl-horizontal">
        <h2><dt><strong>Name:</strong><dt></h2>
        <dd><%= @beer_label.beer_name %></dd>
        <h2><dt><strong>Brewery:</strong></dt></h2>
        <dd><%= @beer_label.brewery %></dd>
        <h2><dt><strong>Origin:</strong></dt></h2>
        <dd><%= @beer_label.origin %></dd>
        <h2><dt><strong>Tags:</strong></dt></h4>
        <dd><%= @beer_label.tag %></dd>
      </dl>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-3 col-md-offset-3">
    <h1>Votes:
        <%= vote_count_display(@beer_label) %>
    </h1>
    <% if user_signed_in? %>
      <div class='dis-like-btn'>
        <%= link_to "Like", upvote_beer_label_path, class:'btn btn-success btn-lg' %>
        <%= link_to "Dislike", downvote_beer_label_path, class:'btn btn-danger btn-lg' %>
      </div>
    <% end %>
  </div>
  <div class="col-md-5">
    <blockquote>
      <h1>"<%= @beer_label.description %>"</h1>
      <small><%= @beer_label.user.email %></small>
    </blockquote>
  </div>
</div>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <% if user_signed_in? %>
      <h2 class="add-comment-field">Add a comment:</h2>
      <%= render "comments/form" %>
    <% end %>
      <h2 class="comments-field">Comments</h2>
      <%= render @beer_label.comments %>
      <%= link_to 'Back to Beer Labels', beer_labels_path %>
  </div>
</div>